### ISSUE TITLE
1. Maintenance Planning Data Download

### ISSUE THREAD

**Issue by sanchaymittal** [sanchaymittal/Rolls-Royce-Challenge#1]
Write: Upload .xlsv file on the network to ensure authenticity and integrity.
Read: Participants authority allows to access the file. 

When a file is uploaded on the network it should link it to the IPFS and saves a hash on the network.  

Participants:
Rolls-Royce TCAv Planners-(Read)- Downloads the Maintenance Planning Data Download file.
Airline's ERP system-(Write)- Uploads the .xlsx file.

**Comment by Man-Jain** [comment]
The IPFS shouldn't be added since this is a private blockchain and ipfs isn't private

**Comment by sanchaymittal** [comment]
> The IPFS shouldn't be added since this is a private blockchain and ipfs isn't private

@Man-Jain For Consortium blockchain, We can create private IPFS Network. Please refer this [link](https://medium.com/@s_van_laar/deploy-a-private-ipfs-network-on-ubuntu-in-5-steps-5aad95f7261b)
